#! /bin/bash
#
#   Run selftests and check memory

#   Valgrind command
VG="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --suppressions=valgrind.supp"

gcc -g -o ztnetstr_selftest ztnetstr_selftest.c  \
    ztns_impl.c \
    ${CFLAGS} ${LDFLAGS} -DHAVE_CONFIG_H -lczmq -lzmq -lcrypto

if [ $? -eq 0 ]; then
    if [ "$1" == "-q" ]; then
        ./ztnetstr_selftest
        exit
    else
        $VG ./ztnetstr_selftest
    fi
fi
rm -f vgcore.*

[ "$1" == "quick" ] && exit
